services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  api:
    container_name: api
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api/src:/app/src
    environment:
      - PORT=80
    env_file:
      - .env

  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
    environment:
      - PORT=80

  database:
    container_name: database
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/db_schema/tables.sql:/docker-entrypoint-initdb.d/01-tables.sql
      - ./database/db_schema/poke_data.sql:/docker-entrypoint-initdb.d/02-poke_data.sql
    
    env_file:
      - .env
